### ISSUE TITLE
Archive repository

### ISSUE THREAD

**Issue by c00kiemon5ter** [IdentityPython/satosa_microservices#13]
I do not have admin rights to do it myself, but I think @leifj has so I'm assigning this to him.

This repository should be [archived](https://help.github.com/articles/archiving-repositories/). Until the new-style micro-services are there, this repository only duplicates effort and makes things harder to follow and maintain.

If possible, issues should be [transferred](https://help.github.com/articles/transferring-an-issue-to-another-repository/) to the `IdentityPython/SATOSA` repository.

**Comment by c00kiemon5ter** [comment]
bump

**Comment by leifj** [comment]
I'm ok giving you admin if you like.

**Comment by c00kiemon5ter** [comment]
Thanks! Just ping me when you do that ;)
